### ISSUE TITLE
scrolling-animations not working

### ISSUE THREAD

**Issue by oscarsmeulders** [CodyHouse/cd-scrolling-animations-changelog#1]
we found out that the 'scrolling-animations' are not working. 
We use the latest macOS, 
Tested on three browsers, Chrome, Safari, Firefox.
Tested these websites:
the demo: https://codyhouse.co/ds/components/app/scrolling-animations
Sketch for client: https://clients.bureauos.design/fizyr/1
And our corporate website: https://bureauos.design/ (bottom of the home)

Some scripts are based on Codyhouse 2.x not not version 3.
Could this be the problem?
thanks in advance

**Comment by claudia-romano** [comment]
Hi there, is the reduced motion option active on the device you're using? If this option is on, the animation does not work.

**Comment by oscarsmeulders** [comment]
Hi Claudia, thank you! The reduced Motion was the issue. After tuning this off all animations worked fine.
